/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <stdio.h>
#include "IfxCcu6_reg.h"
#include "IfxVadc_reg.h"
#include "IfxGtm_reg.h"
#include "IfxPort.h"

#include "Motor.h"
#include "Buzzer.h"
#include "GPIO.h"
#include "ADC.h"
#include "UltraSonic.h"

// Port registers
#define P1_BIT_LSB_IDX          1
#define P2_BIT_LSB_IDX          2

// SCR registers
#define EXIS0_BIT_LSB_IDX       4
#define FEN0_BIT_LSB_IDX        8
#define EIEN0_BIT_LSB_IDX       11
#define INP0_BIT_LSB_IDX        12
#define IGP0_BIT_LSB_IDX        14

//SRC registers
#define SRPN_BIT_LSB_IDX        0
#define TOS_BIT_LSB_IDX         11
#define SRE_BIT_LSB_IDX         10

// Port register index
#define PC1_BIT_LSB_IDX     11
#define PC2_BIT_LSB_IDX     19
#define PC3_BIT_LSB_IDX     27
#define PC5_BIT_LSB_IDX     11
#define PC6_BIT_LSB_IDX     19
#define PC7_BIT_LSB_IDX     27

#define P1_BIT_LSB_IDX      1
#define P2_BIT_LSB_IDX      2
#define P3_BIT_LSB_IDX      3
#define P5_BIT_LSB_IDX      5
#define P6_BIT_LSB_IDX      6
#define P7_BIT_LSB_IDX      7

#define BUTTON_ON       0
#define BUTTON_OFF      1

// scu registers
#define LCK_BIT_LSB_IDX         1
#define ENDINT_BIT_LSB_IDX      0

// CCU60 registers
#define DISS_BIT_LSB_IDX        1
#define DISR_BIT_LSB_IDX        0
#define CTM_BIT_LSB_IDX         7
#define T12PRE_BIT_LSB_IDX      3
#define T12CLK_BIT_LSB_IDX      0
#define T12STR_BIT_LSB_IDX      6
#define T12RS_BIT_LSB_IDX       1
#define INPT12_BIT_LSB_IDX      10
#define ENT12PM_BIT_LSB_IDX     7

// SRC registers
#define SRPN_BIT_LSB_IDX        0
#define TOS_BIT_LSB_IDX         11
#define SRE_BIT_LSB_IDX         10

// VADC registers
#define ANONC_BIT_LSB_IDX       0
#define ASEN0_BIT_LSB_IDX       24
#define CSM0_BIT_LSB_IDX        3
#define PRIO0_BIT_LSB_IDX       0
#define CMS_BIT_LSB_IDX         8
#define FLUSH_BIT_LSB_IDX       10
#define TREV_BIT_LSB_IDX        9
#define ENGT_BIT_LSB_IDX        0
#define RESPOS_BIT_LSB_IDX      21
#define RESREG_BIT_LSB_IDX      16
#define ICLSEL_BIT_LSB_IDX      0
#define VF_BIT_LSB_IDX          31
#define RESULT_BIT_LSB_IDX      0
#define ASSCH7_BIT_LSB_IDX      7

// GTM registers
#define FXCLK_SEL_BIT_LSB_IDX   0
#define EN_FXCLK_BIT_LSB_IDX    22
#define SEL7_BIT_LSB_IDX        14
#define SEL1_BIT_LSB_IDX        2
#define SEL3_BIT_LSB_IDX        6

// GTM - TOM0 registers
#define UPEN_CTRL1_BIT_LSB_IDX  18
#define HOST_TRIG_BIT_LSB_IDX   0
#define ENDIS_CTRL1_BIT_LSB_IDX 2
#define OUTEN_CTRL1_BIT_LSB_IDX 2
#define CLK_SRC_SR_BIT_LSB_IDX  12
#define OSM_BIT_LSB_IDX         26
#define TRIGOUT_BIT_LSB_IDX     24
#define SL_BIT_LSB_IDX          11

#define UPEN_CTRL3_BIT_LSB_IDX  22
#define ENDIS_CTRL3_BIT_LSB_IDX 6
#define OUTEN_CTRL3_BIT_LSB_IDX 6

IfxCpu_syncEvent g_cpuSyncEvent = 0;


int g_gear_state = 1; // D mode: 1, R mode: 2
int g_duty = 0;

void motorDriving(void);
void lightControl(void);
void rearDetection(void);
void gearShift(void);

int core0_main (void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initGTM();
    initMotor();

    initBuzzer();
    initGPIO();
    initVADC();
    initUSonic();

    initCCU60();
    initCCU61();
    initERU();

    GTM_TOM0_TGC0_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;       // trigger update request signal (motor)
    GTM_TOM0_TGC1_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;       // trigger update request signal (buzzer)
    GTM_TOM2_TGC1_GLB_CTRL.U |= 0x1 << HOST_TRIG_BIT_LSB_IDX;       // trigger update request signal (TOM2_11, motor)

    signatureSound();

    while (1)
    {
        motorDriving();
        lightControl();
        gearShift();
        rearDetection();
    }

    return 0;
}

void motorDriving(void)
{
    if (getAccelState() == 1) {
        printf("accel\n");
        g_duty = 2000;
    } else if (getAccelState() == 0)
    {
       if (g_duty != 0)
           g_duty = 1750;
       else
           g_duty = 0;
    }
    if (g_gear_state == 1) {
        motorRun(g_duty, 1);
    } else {
        motorRun(g_duty, 2);
    }

    if (getBrakeState() == 1) {
        g_duty = 0;
        motorBrake();
    }
}

void gearShift(void){
    VADC_startconversion();
    unsigned int adc_result = VADC_readResult();
    if(adc_result >= 2048){
        //R == YELLOW
        setRGBLEDState(1);
        g_gear_state = 2; //R
    }
    else{
        //D == green
        setRGBLEDState(3);
        g_gear_state = 1;  //D
    }
}

void lightControl(void)
{
    if (getBrakeState() == 1) {
        setLED2State(1);
    } else if(getBrakeState() == 0) {
        setLED2State(0);
    }

    if (getAccelState() == 1) {
        if (g_gear_state == 1) {
        } else {
            setLED2State(1);
            for (int i = 0; i < 10000000; ++i);
            setLED2State(0);
            for (int i = 0; i < 10000000; ++i);
        }
    }
}

void rearDetection(void)
{

    if (g_gear_state == 1) {
        return;
    }
    usonicTrigger();
    while(g_range_valid_flag == 0);

    int accelState = getAccelState();
    if (g_range >= 60) {
        deactivateBuzzer();
    } else if (g_range >= 40) {
        beepSound(10000000 * 5, accelState);
    } else if (g_range >= 20) {
        beepSound(10000000*3, accelState);
    } else {
        beepSound(10000000, accelState);
    }
}

